vscode:
  extensions:
    - DotJoshJohnson.xml@2.5.0:j/V3fdZHhHApG0UDF9KLqA==
tasks:
  - init: > 
      export PIPENV_VENV_IN_PROJECT=true;
      pipenv shell;
      pipenv install;
      cd src;
      mkdir output;
  - command: >
      pipenv shell;
      cd src && python ./main.py -h